"""empty message

Revision ID: 1785732cc4d6
Revises: 
Create Date: 2020-11-29 02:48:28.990829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1785732cc4d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miband4_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('serial', sa.String(length=12), nullable=True),
    sa.Column('software_revision', sa.String(length=10), nullable=True),
    sa.Column('hardware_revision', sa.String(length=10), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('auth_key', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('activity_record',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('heartrate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['miband4_devices.id'], ),
    sa.PrimaryKeyConstraint('band_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_record')
    op.drop_table('miband4_devices')
    # ### end Alembic commands ###
